name: Release
on:
  release:
    types: [created]

jobs:
  build-and-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: universal-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target == 'universal-apple-darwin' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm install

      - name: Build (Linux/Windows)
        if: matrix.os != 'macos-latest'
        run: npm run tauri build

      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run tauri build -- --target universal-apple-darwin

      - name: Rename and Upload (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          cd src-tauri/target/release/bundle/nsis
          $exe = Get-ChildItem *.exe | Select-Object -First 1
          Rename-Item $exe.Name "MultiSocials-Setup.exe"
          gh release upload ${{ github.event.release.tag_name }} "MultiSocials-Setup.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename and Upload (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd src-tauri/target/universal-apple-darwin/release/bundle/dmg
          mv *.dmg MultiSocials.dmg
          gh release upload ${{ github.event.release.tag_name }} MultiSocials.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename and Upload (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          cd src-tauri/target/release/bundle/appimage
          mv *.AppImage MultiSocials.AppImage
          gh release upload ${{ github.event.release.tag_name }} MultiSocials.AppImage
          
          cd ../deb
          mv *.deb MultiSocials.deb
          gh release upload ${{ github.event.release.tag_name }} MultiSocials.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}